/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDAGRegistryInterface extends Interface {
  getFunction(nameOrSignature: "nodes" | "resetNode"): FunctionFragment;

  encodeFunctionData(functionFragment: "nodes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "resetNode",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetNode", data: BytesLike): Result;
}

export interface IDAGRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDAGRegistry;
  waitForDeployment(): Promise<this>;

  interface: IDAGRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  nodes: TypedContractMethod<
    [nodeId: BytesLike],
    [
      [string, string, string, string, boolean] & {
        nodeId_: string;
        taskId_: string;
        claimedBy_: string;
        outputHash_: string;
        validated_: boolean;
      }
    ],
    "view"
  >;

  resetNode: TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [nodeId: BytesLike],
    [
      [string, string, string, string, boolean] & {
        nodeId_: string;
        taskId_: string;
        claimedBy_: string;
        outputHash_: string;
        validated_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resetNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  filters: {};
}
