/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SlashingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_WINDOW"
      | "challenge"
      | "challenges"
      | "escrow"
      | "owner"
      | "registry"
      | "renounceOwnership"
      | "resolveChallenge"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeRaised"
      | "FalseChallenge"
      | "OwnershipTransferred"
      | "SlashExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challenge",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "challenges",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveChallenge",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "challenge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ChallengeRaisedEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    challenger: AddressLike,
    accused: AddressLike
  ];
  export type OutputTuple = [
    nodeId: string,
    challenger: string,
    accused: string
  ];
  export interface OutputObject {
    nodeId: string;
    challenger: string;
    accused: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FalseChallengeEvent {
  export type InputTuple = [nodeId: BytesLike, challenger: AddressLike];
  export type OutputTuple = [nodeId: string, challenger: string];
  export interface OutputObject {
    nodeId: string;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashExecutedEvent {
  export type InputTuple = [nodeId: BytesLike, accused: AddressLike];
  export type OutputTuple = [nodeId: string, accused: string];
  export interface OutputObject {
    nodeId: string;
    accused: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SlashingVault extends BaseContract {
  connect(runner?: ContractRunner | null): SlashingVault;
  waitForDeployment(): Promise<this>;

  interface: SlashingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  challenge: TypedContractMethod<
    [nodeId: BytesLike, accused: AddressLike],
    [void],
    "nonpayable"
  >;

  challenges: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        nodeId: string;
        challenger: string;
        accused: string;
        timestamp: bigint;
        resolved: boolean;
      }
    ],
    "view"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveChallenge: TypedContractMethod<
    [nodeId: BytesLike, accusedGuilty: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challenge"
  ): TypedContractMethod<
    [nodeId: BytesLike, accused: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        nodeId: string;
        challenger: string;
        accused: string;
        timestamp: bigint;
        resolved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveChallenge"
  ): TypedContractMethod<
    [nodeId: BytesLike, accusedGuilty: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ChallengeRaised"
  ): TypedContractEvent<
    ChallengeRaisedEvent.InputTuple,
    ChallengeRaisedEvent.OutputTuple,
    ChallengeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "FalseChallenge"
  ): TypedContractEvent<
    FalseChallengeEvent.InputTuple,
    FalseChallengeEvent.OutputTuple,
    FalseChallengeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SlashExecuted"
  ): TypedContractEvent<
    SlashExecutedEvent.InputTuple,
    SlashExecutedEvent.OutputTuple,
    SlashExecutedEvent.OutputObject
  >;

  filters: {
    "ChallengeRaised(bytes32,address,address)": TypedContractEvent<
      ChallengeRaisedEvent.InputTuple,
      ChallengeRaisedEvent.OutputTuple,
      ChallengeRaisedEvent.OutputObject
    >;
    ChallengeRaised: TypedContractEvent<
      ChallengeRaisedEvent.InputTuple,
      ChallengeRaisedEvent.OutputTuple,
      ChallengeRaisedEvent.OutputObject
    >;

    "FalseChallenge(bytes32,address)": TypedContractEvent<
      FalseChallengeEvent.InputTuple,
      FalseChallengeEvent.OutputTuple,
      FalseChallengeEvent.OutputObject
    >;
    FalseChallenge: TypedContractEvent<
      FalseChallengeEvent.InputTuple,
      FalseChallengeEvent.OutputTuple,
      FalseChallengeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SlashExecuted(bytes32,address)": TypedContractEvent<
      SlashExecutedEvent.InputTuple,
      SlashExecutedEvent.OutputTuple,
      SlashExecutedEvent.OutputObject
    >;
    SlashExecuted: TypedContractEvent<
      SlashExecutedEvent.InputTuple,
      SlashExecutedEvent.OutputTuple,
      SlashExecutedEvent.OutputObject
    >;
  };
}
