/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DAGRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimPlanner"
      | "claimSubtask"
      | "escrow"
      | "markValidated"
      | "nodes"
      | "owner"
      | "planners"
      | "registerDAG"
      | "renounceOwnership"
      | "resetNode"
      | "setAddresses"
      | "submitOutput"
      | "taskNodes"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DAGCompleted"
      | "NodeReset"
      | "OutputSubmitted"
      | "OwnershipTransferred"
      | "PlannerSelected"
      | "SubtaskClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimPlanner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSubtask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markValidated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "planners", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerDAG",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetNode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOutput",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskNodes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimPlanner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSubtask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markValidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "planners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDAG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskNodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace DAGCompletedEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeResetEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutputSubmittedEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    agent: AddressLike,
    outputHash: BytesLike
  ];
  export type OutputTuple = [nodeId: string, agent: string, outputHash: string];
  export interface OutputObject {
    nodeId: string;
    agent: string;
    outputHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlannerSelectedEvent {
  export type InputTuple = [taskId: BytesLike, planner: AddressLike];
  export type OutputTuple = [taskId: string, planner: string];
  export interface OutputObject {
    taskId: string;
    planner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtaskClaimedEvent {
  export type InputTuple = [nodeId: BytesLike, agent: AddressLike];
  export type OutputTuple = [nodeId: string, agent: string];
  export interface OutputObject {
    nodeId: string;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAGRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DAGRegistry;
  waitForDeployment(): Promise<this>;

  interface: DAGRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimPlanner: TypedContractMethod<
    [taskId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  claimSubtask: TypedContractMethod<
    [nodeId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  markValidated: TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  nodes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        nodeId: string;
        taskId: string;
        claimedBy: string;
        outputHash: string;
        validated: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  planners: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  registerDAG: TypedContractMethod<
    [taskId: BytesLike, nodeIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetNode: TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  setAddresses: TypedContractMethod<
    [_escrow: AddressLike, _vault: AddressLike],
    [void],
    "nonpayable"
  >;

  submitOutput: TypedContractMethod<
    [nodeId: BytesLike, outputHash: BytesLike],
    [void],
    "nonpayable"
  >;

  taskNodes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimPlanner"
  ): TypedContractMethod<[taskId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "claimSubtask"
  ): TypedContractMethod<[nodeId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markValidated"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        nodeId: string;
        taskId: string;
        claimedBy: string;
        outputHash: string;
        validated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "planners"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerDAG"
  ): TypedContractMethod<
    [taskId: BytesLike, nodeIds: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [_escrow: AddressLike, _vault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitOutput"
  ): TypedContractMethod<
    [nodeId: BytesLike, outputHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskNodes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DAGCompleted"
  ): TypedContractEvent<
    DAGCompletedEvent.InputTuple,
    DAGCompletedEvent.OutputTuple,
    DAGCompletedEvent.OutputObject
  >;
  getEvent(
    key: "NodeReset"
  ): TypedContractEvent<
    NodeResetEvent.InputTuple,
    NodeResetEvent.OutputTuple,
    NodeResetEvent.OutputObject
  >;
  getEvent(
    key: "OutputSubmitted"
  ): TypedContractEvent<
    OutputSubmittedEvent.InputTuple,
    OutputSubmittedEvent.OutputTuple,
    OutputSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlannerSelected"
  ): TypedContractEvent<
    PlannerSelectedEvent.InputTuple,
    PlannerSelectedEvent.OutputTuple,
    PlannerSelectedEvent.OutputObject
  >;
  getEvent(
    key: "SubtaskClaimed"
  ): TypedContractEvent<
    SubtaskClaimedEvent.InputTuple,
    SubtaskClaimedEvent.OutputTuple,
    SubtaskClaimedEvent.OutputObject
  >;

  filters: {
    "DAGCompleted(bytes32)": TypedContractEvent<
      DAGCompletedEvent.InputTuple,
      DAGCompletedEvent.OutputTuple,
      DAGCompletedEvent.OutputObject
    >;
    DAGCompleted: TypedContractEvent<
      DAGCompletedEvent.InputTuple,
      DAGCompletedEvent.OutputTuple,
      DAGCompletedEvent.OutputObject
    >;

    "NodeReset(bytes32)": TypedContractEvent<
      NodeResetEvent.InputTuple,
      NodeResetEvent.OutputTuple,
      NodeResetEvent.OutputObject
    >;
    NodeReset: TypedContractEvent<
      NodeResetEvent.InputTuple,
      NodeResetEvent.OutputTuple,
      NodeResetEvent.OutputObject
    >;

    "OutputSubmitted(bytes32,address,bytes32)": TypedContractEvent<
      OutputSubmittedEvent.InputTuple,
      OutputSubmittedEvent.OutputTuple,
      OutputSubmittedEvent.OutputObject
    >;
    OutputSubmitted: TypedContractEvent<
      OutputSubmittedEvent.InputTuple,
      OutputSubmittedEvent.OutputTuple,
      OutputSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlannerSelected(bytes32,address)": TypedContractEvent<
      PlannerSelectedEvent.InputTuple,
      PlannerSelectedEvent.OutputTuple,
      PlannerSelectedEvent.OutputObject
    >;
    PlannerSelected: TypedContractEvent<
      PlannerSelectedEvent.InputTuple,
      PlannerSelectedEvent.OutputTuple,
      PlannerSelectedEvent.OutputObject
    >;

    "SubtaskClaimed(bytes32,address)": TypedContractEvent<
      SubtaskClaimedEvent.InputTuple,
      SubtaskClaimedEvent.OutputTuple,
      SubtaskClaimedEvent.OutputObject
    >;
    SubtaskClaimed: TypedContractEvent<
      SubtaskClaimedEvent.InputTuple,
      SubtaskClaimedEvent.OutputTuple,
      SubtaskClaimedEvent.OutputObject
    >;
  };
}
