/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDAGRegistry,
  IDAGRegistryInterface,
} from "../../../contracts/SlashingVault.sol/IDAGRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "nodeId",
        type: "bytes32",
      },
    ],
    name: "nodes",
    outputs: [
      {
        internalType: "bytes32",
        name: "nodeId_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "taskId_",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "claimedBy_",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "outputHash_",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "validated_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "nodeId",
        type: "bytes32",
      },
    ],
    name: "resetNode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDAGRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDAGRegistryInterface {
    return new Interface(_abi) as IDAGRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDAGRegistry {
    return new Contract(address, _abi, runner) as unknown as IDAGRegistry;
  }
}
