/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dagRegistrySol from "./DAGRegistry.sol";
export type { dagRegistrySol };
import type * as slashingVaultSol from "./SlashingVault.sol";
export type { slashingVaultSol };
export type { MockERC20 } from "./MockERC20";
export type { SwarmEscrow } from "./SwarmEscrow";
