/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwarmEscrow,
  ISwarmEscrowInterface,
} from "../../../src/SlashingVault.sol/ISwarmEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "slash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwarmEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): ISwarmEscrowInterface {
    return new Interface(_abi) as ISwarmEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISwarmEscrow {
    return new Contract(address, _abi, runner) as unknown as ISwarmEscrow;
  }
}
